aurora/urls.py
from django.contrib import admin
from django.urls import path, include
from home import urls as home_urls
from user import urls as user_urls
from academic import urls as academic_urls
from horary import urls as horary_urls

urlpatterns = [
    path('admin/', admin.site.urls, name = "admin"),
    path('', include(home_urls), name = "home"),
    path('user/', include(user_urls), name = 'user'),
    path('', include(academic_urls), name='academic'),
    path('', include(horary_urls), name='horary'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name='home'),
]

schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from home import urls as home_urls
from .views import showSchedule, showSubjects, newPeriod, deletePeriod, editPeriod, editSubject, deleteSubject, newSubject, newNote, deleteNote, editNote

urlpatterns = [
    path('', include(home_urls), name='home'),
    path('schedule/', showSchedule, name='schedule'),
    path('schedule/newperiod/', newPeriod, name="newPeriod"),
    path('schedule/deleteperiod/', deletePeriod, name="deletePeriod"),
    path('schedule/editperiod/', editPeriod, name="editPeriod"),
    path('subject/periodid=<int:id>/', showSubjects, name='subject'),
    path('subject/editsubject/period=<int:periodId>/', editSubject, name='editSubject'),
    path('subject/deletesubject/period=<int:periodId>/', deleteSubject, name='deleteSubject'),
    path('subject/newsubject/period=<int:periodId>/', newSubject, name='newSubject'),
    path('subject/newnote/period=<int:periodId>/', newNote, name='newNote'),
    path('subject/deletenote/period=<int:periodId>/', deleteNote, name='deleteNote'),
    path('subject/editnote/period=<int:periodId>/', editNote, name='editNote'),
]

academic/models.py
from django.db import models
from user import models as user_models

# Create your models here.
class Period(models.Model):
    year = models.CharField(max_length=6)
    cre = models.DecimalField(max_digits=4, decimal_places=2, default=0, blank=True)
    student = models.ForeignKey(user_models.Student, on_delete=models.PROTECT , null=True, blank=True)

    def __str__(self):
        return str(self.year)

class Subject(models.Model):
    name = models.CharField(max_length=50)
    credits = models.IntegerField(default=0)
    period = models.ForeignKey(Period, on_delete=models.CASCADE, null=True, blank=True)
    student = models.ForeignKey(user_models.Student, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

class Note(models.Model):
    name = models.CharField(max_length=20)
    weight = models.IntegerField(default=1)
    value = models.DecimalField(max_digits=4, decimal_places=2)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    period = models.ForeignKey(Period, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.name + ": " + str(self.value)

academic/forms.py
from django import forms
from .models import Note, Subject, Period

class NoteForm(forms.Form):
    name = forms.CharField(max_length=20)
    weight = forms.IntegerField()
    value = forms.DecimalField(max_digits=4, decimal_places=2)

class SubjectForm(forms.Form):
    name = forms.CharField(max_length=50)
    credits = forms.IntegerField()

class PeriodForm(forms.Form):
    year = forms.CharField(max_length=6)

schedule/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from user import models as user_models
from .models import Period, Subject, Note
from .forms import PeriodForm, SubjectForm, NoteForm

@login_required
def showSchedule(request):
        student = getLoggedStudent(request)

        if(isinstance(student, user_models.Student)):
                studentAllPeriods = Period.objects.filter(student=student)
                return render(request, 'schedule.html', {'periods':studentAllPeriods})

@login_required
def showSubjects(request, id):
        periodSelected = get_object_or_404(Period, pk=id)
        student = getLoggedStudent(request)
        allSubjectsOfThisPeriod = Subject.objects.filter(period=periodSelected, student=student)
        allNotesOfThisSubject = Note.objects.filter(period=periodSelected)

        context = {
                'subjects':allSubjectsOfThisPeriod, 
                'periodId':id,
                'allNotes':allNotesOfThisSubject,
                'period':periodSelected
                }
        return render(request, 'subjects.html', context)

@login_required
def getLoggedStudent(request):
        userDjango = request.user
        userAurora = user_models.User.objects.get(user=userDjango)
        student = user_models.Student.objects.get(user=userAurora)
        return student

@login_required
def newPeriod(request):
        form = PeriodForm(request.POST or None)
        if(request.method == 'POST'):
                if(form.is_valid()):
                        year = form.cleaned_data['year']
                        student = getLoggedStudent(request)
                        newPeriod = Period(year=year, student=student)
                        newPeriod.save()

        return redirect('schedule')

@login_required
def deletePeriod(request):
        if(request.method == 'POST'):
                id = request.POST.get('id')
                loggedStudent = getLoggedStudent(request)
                periodSelected = get_object_or_404(Period, pk=id, student=loggedStudent)
                periodSelected.delete()
                
        return redirect('schedule')

@login_required
def editPeriod(request):
        if(request.method == 'POST'):
                id = request.POST.get('id')
                year = request.POST.get('year')
                loggedStudent = getLoggedStudent(request)
                periodSelected = get_object_or_404(Period, pk=id, student=loggedStudent)
                periodSelected.year = year
                periodSelected.save()

        return redirect('schedule')

@login_required
def editSubject(request, periodId):
        if(request.method == 'POST'):
                loggedStudent = getLoggedStudent(request)
                periodSelected = get_object_or_404(Period, pk=periodId, student=loggedStudent)

                id = request.POST.get('id')
                name = request.POST.get('name')
                credits = request.POST.get('credits')
                subjectSelected = get_object_or_404(Subject, pk=id, period=periodSelected)
                subjectSelected.name = name
                subjectSelected.credits = credits
                subjectSelected.save()

        return redirect('subject', periodId)

@login_required
def deleteSubject(request, periodId):
        if(request.method == 'POST'):
                loggedStudent = getLoggedStudent(request)
                periodSelected = get_object_or_404(Period, pk=periodId, student=loggedStudent)

                id = request.POST.get('id')
                subjectSelected = get_object_or_404(Subject, pk=id, period=periodSelected)
                subjectSelected.delete()

        return redirect('subject', periodId)

@login_required
def newSubject(request, periodId):
        form = SubjectForm(request.POST or None)
        if(request.method == 'POST'):
                if(form.is_valid()):
                        loggedStudent = getLoggedStudent(request)
                        periodSelected = get_object_or_404(Period, pk=periodId, student=loggedStudent)

                        name = form.cleaned_data['name']
                        credits = form.cleaned_data['credits']

                        newSubject = Subject(name=name, credits=credits, period=periodSelected, student=loggedStudent)
                        newSubject.save()

        return redirect('subject', periodId)

@login_required
def newNote(request, periodId):
        form = NoteForm(request.POST or None)
        if(request.method == 'POST'):
                if(form.is_valid()):
                        loggedStudent = getLoggedStudent(request)
                        periodSelected = get_object_or_404(Period, pk=periodId, student=loggedStudent)
                        
                        subjectId = request.POST.get('id')
                        name = form.cleaned_data['name']
                        weight = form.cleaned_data['weight']
                        value = form.cleaned_data['value']

                        subjectSelected = get_object_or_404(Subject, pk=subjectId, period=periodSelected, student=loggedStudent)

                        newNote = Note(name=name, weight=weight, value=value, subject=subjectSelected, period=periodSelected)
                        newNote.save()
        return redirect('subject',periodId)

@login_required
def deleteNote(request, periodId):
        if(request.method == 'POST'):
                loggedStudent = getLoggedStudent(request)
                periodSelected = get_object_or_404(Period, pk=periodId, student=loggedStudent)

                noteId = request.POST.get('id_note')
                selectedSubjectId = request.POST.get('id_subject')

                selectedSubject = get_object_or_404(Subject, pk=selectedSubjectId, period=periodSelected, student=loggedStudent)

                noteSelected = get_object_or_404(Note, pk=noteId, subject=selectedSubject, period=periodSelected)
                noteSelected.delete()

        return redirect('subject',periodId)

@login_required
def editNote(request, periodId):
        if(request.method == 'POST'):
                loggedStudent = getLoggedStudent(request)
                periodSelected = get_object_or_404(Period, pk=periodId, student=loggedStudent)
                
                noteId = request.POST.get('id_note')
                subjectId = request.POST.get('id_subject')
                name = request.POST.get('name')
                weight = request.POST.get('weight')
                value = request.POST.get('value')

                selectedSubject = get_object_or_404(Subject, pk=subjectId, period=periodSelected, student=loggedStudent)

                selectedNote = get_object_or_404(Note, pk=noteId, subject=selectedSubject, period=periodSelected)

                selectedNote.name = name
                selectedNote.weight = int(weight)
                selectedNote.value = int(value)

                selectedNote.save()

        return redirect('subject',periodId)
        

schedule/templates/schedule.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Agenda{% endblock %}

{% block functions %}
    <h3>Funções</h3>
    <!-- Button trigger modal to create new period -->
    <button id="new_period" type="button" class="btn btn-success" data-toggle="modal" data-target="#newPeriodModal">Novo Periodo</button>
{% endblock %}

{% block feed %}
    <h3>Seus periodos cadastrados</h3>
    {% if periods|length == 0 %}
        <p style="color: #000000; text-align: center">Você não possui periodos dacastrados.</p>
    {% endif %}
    {% for period in periods %}
        <ul class="period_list">
            <div class="period">
                <li>
                    <a href="{% url 'subject' period.id %}" class="period-year">{{period.year}}</a>

                    <!-- Button trigger modal to delete selected period -->
                    <a href="" class="trash-item"  data-toggle="modal" data-target="#deletePeriodModal" data-whateverid="{{period.id}}" data-whatevername="{{period.year}}">
                        <i class="fa fa-trash"></i>
                    </a>

                    <!-- Button trigger modal to edit selected period -->
                    <a href="" class="edit-item"  data-toggle="modal" data-target="#editPeriodModal" data-whateverid="{{period.id}}" data-whatevername="{{period.year}}">
                        <i class="fa fa-edit"></i>
                    </a>
                    
                </li>
            </div>
        </ul> 
    {% endfor %}

    <!-- Modal Form - Edit selected Period -->

    <div class="modal fade" id="editPeriodModal" tabindex="-1" role="dialog" aria-labelledby="editPeriodModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="editPeriodModalLabel">Editar Periodo</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          
                </div>
                <div class="modal-body">
                    <div class="editPeriodForm">
                        <form method="POST" id="editPeriodForm" name="editPeriodForm" action="{% url 'editPeriod' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="hidden" id="id_period" name="id">
                                <label class="control-label" for="id_year">Ano/Periodo</label>
                                <div class=" ">
                                    <input type="text" name="year" class=" form-control" id="id_year" maxlength="6">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-success" form="editPeriodForm"">Salvar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Form - Delete selected Period -->

    <div class="modal fade" id="deletePeriodModal" tabindex="-1" role="dialog" aria-labelledby="deletePeriodModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" id="delete-modal">
                    <h5 class="modal-title" id="deletePeriodModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Ao clicar em "Sim", todas as disciplinas desse periodo também serão apagadas, juntamente com todas as notas relacionadas a elas.</p>
                    <form action="{% url 'deletePeriod' %}" method="POST" name="deletePeriodForm" id="deletePeriodForm">
                        {% csrf_token %}
                        <input type="hidden" id="id_period" name="id">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                    <!-- To work delete button -->
                    <button type="submit" id="confirm-delete" class="btn btn-danger" form="deletePeriodForm">Sim</button>
                </div>
            </div>
        </div>
    </div>
  
    <!-- Modal Form - Create new Period -->

    <div class="modal fade" id="newPeriodModal" tabindex="-1" role="dialog" aria-labelledby="newPeriodModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newPeriodModalLabel">Novo Periodo</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          
                </div>
                <div class="modal-body">
                    <div class="newPeriodForm">
                        <form method="POST" id="newPeriodForm" name="newPeriodForm" action="{% url 'newPeriod' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label" for="id_year">Ano/Periodo</label>
                                <div class=" ">
                                    <input type="text" name="year" class=" form-control" id="id_year" maxlength="6">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-success" form="newPeriodForm"">Salvar</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block infos %}
<h3>Informações</h3>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $('#deletePeriodModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var recipientid = button.data('whateverid')
            var recipientname = button.data('whatevername')

            var modal = $(this) 
            modal.find('.modal-title').text('Confirma apagar periodo ' + recipientname + "?")
            modal.find('#id_period').val(recipientid)
        })

        $('#editPeriodModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var recipientid = button.data('whateverid')
            var recipientname = button.data('whatevername')

            var modal = $(this) 
            modal.find('#id_year').val(recipientname)
            modal.find('#id_period').val(recipientid)
        })
    </script>
{% endblock%}