aurora/urls.py
from django.contrib import admin
from django.urls import path, include
from home import urls as home_urls
from user import urls as user_urls
from academic import urls as academic_urls
from horary import urls as horary_urls

urlpatterns = [
    path('admin/', admin.site.urls, name = "admin"),
    path('', include(home_urls), name = "home"),
    path('user/', include(user_urls), name = 'user'),
    path('', include(academic_urls), name='academic'),
    path('', include(horary_urls), name='horary'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name='home'),
]

horary/urls.py
from django.contrib import admin
from django.urls import path, include
from home import urls as home_urls
from .views import showHorary

urlpatterns = [
    path('', include(home_urls), name='home'),
    path('horary/', showHorary, name='horary'),
]

horary/models.py
from django.db import models
from academic import models as academic_models
# Create your models here.

class Horary(models.Model):
    initials = models.CharField(max_length=10)
    hourStart = models.CharField(max_length=5)
    hourEnd = models.CharField(max_length=5)
    classroom = models.CharField(max_length=10)
    subject = models.OneToOneField(academic_models.Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.initials

horary/forms.py
from django import forms
from .models import Horary

class HoraryForm(forms.Form):
    initials = forms.CharField(max_length=10)
    hourStart = forms.CharField(max_length=5)
    hourEnd = forms.CharField(max_length=5)
    classroom = forms.CharField(max_length=10)

horary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from academic import views as academic_views
from academic import models as academic_models
import re

@login_required
def showHorary(request):
    loggedStudent = academic_views.getLoggedStudent(request)
    periods = academic_models.Period.objects.filter(student=loggedStudent)

    if(request.method == 'POST'):
        optionSelected = request.POST.get('period-selected')
        optionList = optionSelected.split('-')
        periodSelectedId = int(optionList[1])

        periodSelected = get_object_or_404(academic_models.Period, pk=periodSelectedId, student=loggedStudent)
        print(periodSelected)
        
        periods = academic_models.Period.objects.filter(student=loggedStudent)
        allSubjectsOfThisPeriod = []
        allSubjectsOfThisPeriod = academic_models.Subject.objects.filter(period=periodSelected, student=loggedStudent)
        context = {
            "currentPeriod":periodSelected,
            "periods":periods,
            "subjects":allSubjectsOfThisPeriod,
        }
    else:
        lastRegistredPeriod = None
        allSubjectsOfThisPeriod = []
        if(len(periods) > 0):
            lastRegistredPeriod = periods[len(periods)-1]
            allSubjectsOfThisPeriod = academic_models.Subject.objects.filter(period=lastRegistredPeriod, student=loggedStudent)

        context = {
            "currentPeriod":lastRegistredPeriod,
            "periods":periods,
            "subjects":allSubjectsOfThisPeriod,
        }
    
    return render(request, 'horary.html', context) 

horary/templates/horary.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/horary_style.css' %}">

{% endblock%}
{% block title %}Horarios{% endblock %}

{% block header %}

{% endblock %}

{% block functions %}
<h3>Funções</h3>
    
{% endblock %}

{% block feed %}

{% if currentPeriod == None %} 
    <h3>Horários</h3>
{% else %}
    <h3>Horários do periodo {{currentPeriod}}</h3>
{% endif %}

<div class="table-responsive-md" id="horaryTable">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col" style="text-align: center" id="selectPeriod">
                    
                    <form class="form" name="selectPeriodForm" id="selectPeriodForm" method="POST" action="{% url 'horary' %}">
                        {% csrf_token %}
                        <select class="custom-select" id="period" name="period-selected">
                            <option selected hidden>Selecione</option>
                            {% for period in periods %}
                                <option value="period-{{period.id}}">{{period}}</option>
                            {% endfor %}
                        </select>
                    </form>
                    <button type="submit" class="btn btn-secondary" id="btn-see" form="selectPeriodForm">Ver</button>

                </th>
                <th scope="col" style="text-align: center">Domingo</th>
                <th scope="col" style="text-align: center">Segunda</th>
                <th scope="col" style="text-align: center">Terça</th>
                <th scope="col" style="text-align: center">Quarta</th>
                <th scope="col" style="text-align: center">Quinta</th>
                <th scope="col" style="text-align: center">Sexta</th>
                <th scope="col" style="text-align: center">Sábado</th>
            </tr>
        </thead>
        <tbody id="tbody">
            
        </tbody>
    </table>
</div>

<!-- Modal Form - add new horary -->

<div class="modal fade" id="addHoraryModal" tabindex="-1" role="dialog" aria-labelledby="addHoraryLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addHoraryModalLabel">Novo Horário</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        
            </div>
            <div class="modal-body">
                <div class="addHoraryForm">
                    <form method="POST" id="addHoraryForm" name="addHoraryForm" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label" for="id_initials">Sigla</label>
                            <div class=" ">
                                <input type="text" name="initials" class=" form-control" id="initials" maxlength="10">
                            </div>

                            <label class="control-label" for="id_initials">Hora de início</label>
                            <div class=" ">
                                <input type="text" name="initials" class=" form-control" id="start-hour" maxlength="6">
                            </div>

                            <label class="control-label" for="id_initials">Hora de terminio</label>
                            <div class=" ">
                                <input type="text" name="initials" class=" form-control" id="end-hour" maxlength="6">
                            </div>

                            <label class="control-label" for="id_initials">Sala</label>
                            <div class=" ">
                                <input type="text" name="initials" class=" form-control" id="classroom" maxlength="10">
                            </div>

                            <label class="control-label" for="id_initials">Disciplina</label>

                            <form class="form" name="selectSubjectForm" id="selectSubjectForm" style="margin-top: 8px; margin-bottom: 8px">
                                <select class="custom-select" id="subject" name="subject-selected">
                                    <option selected hidden>Selecione</option>
                                    {% for subject in subjects %}
                                        <option value="subject-{{subject.id}}" style="padding: 4px;" id="selected-subject-{{subject.id}}">{{subject}}</option>
                                    {% endfor %}
                                </select>
                            </form>

                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-success" id="btnSendNewHorary">Salvar</button>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block infos %}
<h3>Informações</h3>
{% endblock %}

{% block scripts %}

<script>
    window.onload = fillTable();

    function fillTable(disciplinas){
        var lines = 14;
        var coluns = 7;
        var horaries = ["08h-09h", "09h-10h", "10h-11h", "11h-12h", "12h-13h", "13h-14h","14h-15h", "15h-16h", "16h-17h", "17h-18h","18h-19h", "19h-20h", "20h-21h", "21h-22h"];

        for(var i = 0; i < lines; i++){
            var tr = document.createElement("tr");
            var th = document.createElement("th");
            th.scope = "row"
            th.innerHTML = horaries[i];
            th.style = "text-align: center";
            tr.appendChild(th);
            document.getElementById("tbody").appendChild(tr)
            for(var j = 0; j < coluns; j++){
            var td = document.createElement("td");
            var htmlAdd = '<a href="" style="margin-left: 40px; color:#000000;" class="add-item"  data-toggle="modal" data-target="#addHoraryModal"><i class="fa fa-plus-square"></i></a>';
            td.innerHTML = htmlAdd;
            tr.appendChild(td);
            }
        }
    }

    function verificar() {
        $("#period option:selected").each(function() {
            console.log($(this).val()); // valor 
            console.log($(this).text()); // texto
        });
    }


    $("#btnSendNewHorary").click(function(){
        var data = [];
        $("#initials").each(function(){
            data[$(this).attr("name")] = $(this).val();
        });

        console.log(data);

        $("#start-hour").each(function(){
            data[$(this).attr("name")] = $(this).val();
        });

        console.log(data);

        $("#end-hour").each(function(){
            data[$(this).attr("name")] = $(this).val();
        });

        console.log(data);

        $("#classroom").each(function(){
            data[$(this).attr("name")] = $(this).val();
        });

        console.log(data);
    });
    
</script>

{% endblock%}